#language: "python"
#python:
#  - "3.7"
#install:
#  - "sudo apt-get update"
#  - "wget https://repo.continuum.io/miniconda/Minicond3-latest-x86_64.sh -O miniconda.sh"
#  - "/bin/bash miniconda.sh -b -p $HOME/miniconda"
#  - "export PATH=$HOME/miniconda/bin:$PATH"
#  - "hash -r"
#  - "conda config --set always_yes yes --set changeps1 no"
#  - "conda update -q conda"
#
#  - "conda create -f admin/env/lnx.yml"
#  - ". activate sigai-auto-admin"
#
#script:
#  - "sh auto-admin.sh"

env:
  global:
  - ENCRYPTION_LABEL: 2243fdfd4261

matrix:
  include:
    - language: python
      python: 3.6.5
      install:
        - sudo apt-get update
        - curl -fsSL https://repo.continuum.io/miniconda/Miniconda2-4.5.4-Linux-x86_64.sh -o miniconda.sh
        - /bin/bash miniconda.sh -b -p $HOME/miniconda
        - export PATH=$HOME/miniconda/bin:$PATH
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda env create -f admin/env/lnx.yml
        - source activate sigai-auto-admin
    - language: ruby
      rvm: 2.4.2
      install:
        - curl -fsSL https://raw.githubusercontent.com/ucfsigai/data-science/master/docs/Gemfile -o Gemfile
        - bundle install --gemfile=Gemfile
      cache: bundler
      sudo: false

jobs:
  include:
    - stage:  "rectify_notebooks"
      script: python -m admin update --notebooks
    - stage:  "convert_notebooks_to_jekyll_posts"
      script:  python -m admin make --jekyll-posts
    - stage:  "rebuild_dsg.ucfsigai.org"
      script: bash admin/sites/deploy.sh
