## Base images of each respective Dockerfile
base:
  cpu: "library/ubuntu:16.04"
  gpu: "nvidia/cuda:9.1-base-ubuntu16.04"
  # gpu-amd:    ""
  ## Currently, only support NVIDIA – GPU passthrough to Docker containers
  ##   on AMD platforms are significantly more involved

## Image Meta, specify `<host>/<name>:` of Docker tagging system
image:
  host: ucfsigai
  name: dsg

## Args to replace `%%<text>%%` in `template.Dockerfile`
build-args:
  conda: "4.4.10"

## Runtime arguments
start-args:
  volumes:
    - "$(pwd):/notebooks"
    - "$(pwd)/udocker/.jupyter:/root/.jupyter"
  ports:
    ## port numbers based on old 9-key alpha keyboard
    - "33360:8888"