remote_theme: "ucfsigai/theme@master"

future: true

## site title
title: Data Science Group &ndash; SIGAI@UCF

## this should become a google group, in a few weeks (04/30/18)
email: ucfsigai@gmail.com

## SIGAI@UCF mission
description: >-
  The Data Science Group of SIGAI@UCF hosts lectures, workshops, and the 
  competitive data science team. The lectures and workshops foster and refine 
  interest in data science and machine learning, preparing students for 
  industry and research positions.

## subpath, for the site, it's just "/"
baseurl: "/data-science"
## protocol (http[s]) and tld (ucfsigai.github.io)
url: "https://ucfsigai.org"
social:
  repo: ucfsigai/data-science
  slack: https://ucfsigai.slack.com/messages/CA6CUQWV7/

# Build settings
markdown: kramdown
plugins:
  # - jekyll-feed
  - jekyll-postfiles

defaults:
  - scope:
      type: posts
    values:
      layout: club-meeting
      permalink: /:categories/:title/
  - scope:
      type: "semidx"
    values:
      layout: club-syllabi

collections:
  semidx:
    output: true
    permalink: /:title/
  signin:
    output: true
    permalink: /:title/signin/
  signup:
    output: true
    permalink: /:title/signup/

exclude:
  - docker-compose.yml
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - .ruby-version
