source "https://rubygems.org"

gem "jekyll"

group :jekyll_plugins do
    gem "github-pages"
    # gem "jemoji"
    # gem "jekyll-remote-theme"
    # gem "jekyll-postfiles"
    # gem "jekyll-avatar"
    # gem "jekyll-redirect-from"
    # gem "jekyll-mentions"
    # gem "jekyll-titles-from-headings"
    # gem "jekyll-sass-converter"
    # gem "jekyll-relative-links"
end