name: "Crontab for Core"

on:
  schedule:
    - cron: "*  3 * * *"  # run every 3am
    - cron: "* 16 * * *"  # run every 4pm

jobs:
  daily-site-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest master branch
        uses: actions/checkout@v2
      # - name: