name: "Semester Setup"

on:
  schedule:
    - cron: "0 0 20-28 12 *"  # Spring semester
    - cron: "0 0 12-20  8 *"  # Fall semester

jobs:
  deploy-semester:
    runs-on: ubuntu-latest
    env:
      GROUP: "core"

    steps:
      # Checkout repositories
      - name: "${GROUP}: Checkout latest master branch"
        uses: actions/checkout@v2
        with:
          repository: "ucfai/${GROUP}"
          path: "${GROUP}"
      - name: "ucfai.org: Checkout latest master branch"
        uses: actions/checkout@v2
        with:
          repository: "ucfai/ucfai.org"
          path: ucfai.org
      # Pull and run autobot within container
      - name: "Pull autobot/production:latest"
        run: docker pull docker.pkg.github.com/ucfai/bot/production:latest
      - name: "Setup semester"
          docker run \
            -v ${GROUP}:/ucfai/${GROUP} \
            -v ucfai.org:/ucfai.org \
            core semester-setup
      # Push updates to ${GROUP}
      - name: "Commit updates on ${GROUP}"
        run: |
          cd ${WORKSPACE}/${GROUP}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "setup semester" -a
      - name: "Push changes to ${GROUP}"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # Push updates to ucfai.org
      - name: "Commit updates on ucfai.org"
        run: |
          cd ${WORKSPACE}/ucfai.org
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "add semester to website" -a
      - name: "Push changes to ${GROUP}"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}